#define ADC0_CHANNEL  			0
#define ADC1_CHANNEL  			1
#define UART0_CHANNEL 			2
#define UART1_CHANNEL 			3

#define PDMA_CH_MCC_CA          15 
#define PDMA_CH_MCC             14 
#define PDMA_CH_SSI1_RX         13 
#define PDMA_CH_SSI1_TX         12 
#define PDMA_CH_SSI0_RX         11 
#define PDMA_CH_SSI0_TX         10 
#define PDMA_CH_I2C1_RX         9  
#define PDMA_CH_I2C1_TX         8  
#define PDMA_CH_I2C0_RX         7  
#define PDMA_CH_I2C0_TX         6  
#define PDMA_CH_UART2_RX        5  
#define PDMA_CH_UART2_TX        4  
#define PDMA_CH_UART1_RX        3  
#define PDMA_CH_UART1_TX        2  
#define PDMA_CH_UART0_RX        1  
#define PDMA_CH_UART0_TX        0  
